import '../styles/globals.css';

import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { Inter } from 'next/font/google';

import { detectDevice } from '@/lib/detectDevice';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Side Nav w/ submenus',
  description: 'Generated by create next app',
};

const DesktopComponent = dynamic(
  () => import('../components/DesktopComponent'),
);
const MobileComponent = dynamic(() => import('../components/MobileComponent'));

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isMobile } = await detectDevice();

  const Component = isMobile ? MobileComponent : DesktopComponent;
  console.log('isMobile', isMobile);

  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <Component>{children}</Component>
      </body>
    </html>
  );
}
