import '../styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/components/HeaderDesktop';
import HeaderMobile from '@/components/HeaderMobile';
import MarginWidthWrapper from '@/components/MarginWidthWrapper';
import PageWrapper from '@/components/PageWrapper';
import SideNav from '@/components/SideNav';
import { isMobileDevice } from '@/lib/deviceDetection';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Side Nav w/ submenus',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isMobile = await isMobileDevice();

  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <div className="flex">
          <SideNav isMobile={isMobile} />
          <main className="flex-1">
            <MarginWidthWrapper isMobile={isMobile}>
              <Header isMobile={isMobile} />
              <HeaderMobile isMobile={isMobile} />
              <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}
